name: weather_app
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  flutter_screenutil: ^5.9.3
  google_fonts: ^6.3.2
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.1
  simple_gradient_text: ^1.3.0
  intl: ^0.20.2
  fl_chart: ^1.0.0
  url_launcher: ^6.3.2
  linked_scroll_controller: ^0.2.0
  smooth_page_indicator: ^1.2.1
  lottie: ^3.3.2
  dotlottie_loader: ^0.0.5
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  video_player: ^2.10.0


dev_dependencies:
  flutter_native_splash: ^2.4.7
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/videos/




